$ErrorActionPreference='Stop'
function A([bool]$ok,[string]$m){if(-not $ok){throw $m}}
function Godot([string]$app){$r=Join-Path $app 'toolchains\godot';$g=Get-ChildItem $r -Filter '*_console.exe' -File -ErrorAction SilentlyContinue|Select-Object -First 1;if(-not$g){$g=Get-ChildItem $r -Filter 'Godot_v4*.exe' -File -ErrorAction SilentlyContinue|Where-Object{$_.Name-notmatch'_console\.exe$'}|Select-Object -First 1};if(-not$g){throw'Bundled Godot missing'};return $g.FullName}
function Smoke([string]$g,[string]$n){$d=Join-Path $env:RUNNER_TEMP "smoke-final-$n";Remove-Item $d -Recurse -Force -ErrorAction SilentlyContinue;New-Item -ItemType Directory -Force $d|Out-Null;"config_version=5`n[application]`nrun/main_scene=`"res://main.tscn`"`n"|Set-Content -Encoding utf8NoBOM (Join-Path $d 'project.godot');"extends Node`nfunc _ready():`n print(`"FORGE_GODOT_SMOKE_OK`")`n get_tree().quit()`n"|Set-Content -Encoding utf8NoBOM (Join-Path $d 'main.gd');"[gd_scene load_steps=2 format=3]`n[ext_resource path=`"res://main.gd`" type=`"Script`" id=`"1`"]`n[node name=`"Main`" type=`"Node`"]`nscript=ExtResource(`"1`")`n"|Set-Content -Encoding utf8NoBOM (Join-Path $d 'main.tscn');$o=(&$g --headless --path $d 2>&1|Out-String);A ($LASTEXITCODE-eq 0-and$o-match'FORGE_GODOT_SMOKE_OK') "Final Godot smoke failed $o"}
A (Test-Path $env:PATCHED) 'Prepared 0.38.3 app is missing.'
Remove-Item builder -Recurse -Force -ErrorAction SilentlyContinue;New-Item -ItemType Directory builder|Out-Null;Push-Location builder
'{"name":"forge-studio","version":"0.38.3","description":"Forge Studio reliability and workbench UX release","author":"Ratwaredev","license":"MIT","devDependencies":{"electron-builder":"26.15.3"},"build":{"appId":"com.ratwaredev.forgestudio","productName":"Forge Studio","electronVersion":"43.2.0","generateUpdatesFilesForAllChannels":true,"directories":{"output":"release"},"win":{"target":["nsis"]},"nsis":{"oneClick":false,"perMachine":false,"allowToChangeInstallationDirectory":true,"createDesktopShortcut":true,"createStartMenuShortcut":true,"deleteAppDataOnUninstall":false,"artifactName":"Forge-Studio-Setup-${version}-${arch}.${ext}"},"publish":[{"provider":"github","owner":"Ratwaredev","repo":"forge-studio-releases","releaseType":"release"}]}}'|Set-Content -Encoding utf8NoBOM package.json
npm install;A ($LASTEXITCODE-eq 0) 'Unable to install electron-builder.';$builder=Resolve-Path 'node_modules/.bin/electron-builder.cmd';$env:CSC_IDENTITY_AUTO_DISCOVERY='false';&$builder --prepackaged "$env:PATCHED" --win nsis --x64 --publish never;$code=$LASTEXITCODE;Pop-Location;A ($code-eq 0) 'electron-builder failed.'
$name='Forge-Studio-Setup-0.38.3-x64.exe';$installer="builder/release/$name";$blockmap="$installer.blockmap";$latest='builder/release/latest.yml';foreach($f in @($installer,$blockmap,$latest)){A (Test-Path $f) "Missing artifact $f"};A ((Get-Item $installer).Length-gt 150MB) 'Installer too small to retain bundled Godot.';$feed=Get-Content $latest -Raw;A ($feed-match'(?m)^version:\s*0\.38\.3\s*$'-and$feed-match[regex]::Escape($name)) 'Generated updater feed is wrong.'
if($env:BASE_INSTALL){$u=Join-Path $env:BASE_INSTALL 'Uninstall Forge Studio.exe';if(Test-Path $u){Start-Process $u -ArgumentList '/S' -Wait|Out-Null}}
$verify=Join-Path $env:RUNNER_TEMP 'forge-0383-verify';Remove-Item $verify -Recurse -Force -ErrorAction SilentlyContinue;$p=Start-Process (Resolve-Path $installer) -ArgumentList '/S',"/D=$verify" -Wait -PassThru;A ($p.ExitCode-eq 0) "0.38.3 install failed $($p.ExitCode)";$app=Join-Path $verify 'resources\app';A ((node -p "require('$($app.Replace('\','/'))/package.json').version")-eq'0.38.3') 'Fresh install version wrong.';$g=Godot $app;$gv=(&$g --version 2>&1|Out-String).Trim();A ($gv-match'^4\.7\.1') "Fresh Godot wrong $gv";$surface=Get-Content (Join-Path $app 'public\product-surfaces.js') -Raw;$appjs=Get-Content (Join-Path $app 'public\app.js') -Raw;$agent=Get-Content (Join-Path $app 'dist\agent\index.js') -Raw;$guard=Get-Content (Join-Path $app 'public\forge-runtime-guard.js') -Raw;$idx=Get-Content (Join-Path $app 'public\index.html') -Raw;A ($surface-notmatch'MutationObserver|setInterval\(render') 'Renderer regression in final install.';A ($appjs-notmatch'\["godot", "next", "vite", "static"\]\.includes\(kind\)') 'Godot still defaults embedded.';A ($appjs-match'2800') 'Reduced idle poll missing.';A ($agent-notmatch'isRun \|\| customGodotValidation') 'Duplicate Godot import remains.';A ($guard-match'Jugá, corregí y entregá sin salir de Forge') 'Workbench UX missing.';A ($idx-match'forge-runtime-guard\.js\?build=forge-v0383') 'Cache key wrong.';Smoke $g 'installed'
$hash=(Get-FileHash $installer -Algorithm SHA256).Hash.ToLowerInvariant();"$hash  $name"|Set-Content -Encoding ascii 'builder/release/SHA256SUMS.txt';Write-Host "FORGE_0383_INSTALLER_OK Godot=$gv SHA256=$hash"
@"
# Forge Studio v0.38.3

Reliability and workbench UX release built on verified 0.38.2.

- Godot projects open natively by default instead of attempting Web export first.
- Native Run skips the duplicate pre-import pass; explicit Validate still performs the Godot import check.
- Keeps bundled official Godot Engine 4.7.1-stable x64 and runs a real scene before and after packaging.
- Removes the once-per-second product-surface rerender and reduces idle bootstrap polling.
- Makes the workflow explicit: Run, Open Godot/project, Validate, Capture and Export.
- Shows elapsed startup time and actionable failures instead of an unexplained spinner.
- Preserves the 0.38.1 renderer fix and 0.38.2 runtime preflight.
"@|Set-Content -Encoding utf8 'builder/release/RELEASE_NOTES.md'
$repo=$env:GITHUB_REPOSITORY;if(-not$repo){$repo='Ratwaredev/forge-studio-releases'};$tag='v0.38.3';$assets=@($installer,$blockmap,$latest,'builder/release/SHA256SUMS.txt');if(gh release view $tag --repo $repo 2>$null){gh release upload $tag @assets --repo $repo --clobber;gh release edit $tag --repo $repo --title 'Forge Studio v0.38.3' --notes-file 'builder/release/RELEASE_NOTES.md' --latest}else{gh release create $tag @assets --repo $repo --target main --title 'Forge Studio v0.38.3' --notes-file 'builder/release/RELEASE_NOTES.md' --latest}
$pub=Join-Path $env:RUNNER_TEMP 'forge-0383-published';Remove-Item $pub -Recurse -Force -ErrorAction SilentlyContinue;New-Item -ItemType Directory -Force $pub|Out-Null;gh release download $tag --repo $repo --dir $pub;foreach($f in @($name,"$name.blockmap",'latest.yml','SHA256SUMS.txt')){A (Test-Path (Join-Path $pub $f)) "Published asset missing $f"};$actual=(Get-FileHash (Join-Path $pub $name) -Algorithm SHA256).Hash.ToLowerInvariant();$declared=((Get-Content (Join-Path $pub 'SHA256SUMS.txt') -Raw).Trim().Split(' ')[0]).ToLowerInvariant();A ($actual-eq$hash-and$actual-eq$declared) 'Published checksum mismatch.';$pf=Get-Content (Join-Path $pub 'latest.yml') -Raw;A ($pf-match'(?m)^version:\s*0\.38\.3\s*$'-and$pf-match[regex]::Escape($name)) 'Published latest.yml wrong.';Write-Host "FORGE_0383_RELEASE_OK $actual"
