$ErrorActionPreference='Stop'
function A([bool]$ok,[string]$m){if(-not $ok){throw $m}}
function Godot([string]$app){$r=Join-Path $app 'toolchains\godot';$g=Get-ChildItem $r -Filter '*_console.exe' -File -ErrorAction SilentlyContinue|Select-Object -First 1;if(-not $g){$g=Get-ChildItem $r -Filter 'Godot_v4*.exe' -File -ErrorAction SilentlyContinue|Where-Object{$_.Name-notmatch'_console\.exe$'}|Select-Object -First 1};if(-not $g){throw'Bundled Godot missing'};return $g.FullName}
function Smoke([string]$g,[string]$n){$d=Join-Path $env:RUNNER_TEMP "smoke-$n";Remove-Item $d -Recurse -Force -ErrorAction SilentlyContinue;New-Item -ItemType Directory -Force $d|Out-Null;"config_version=5`n[application]`nrun/main_scene=`"res://main.tscn`"`n"|Set-Content -Encoding utf8NoBOM (Join-Path $d 'project.godot');"extends Node`nfunc _ready():`n print(`"FORGE_GODOT_SMOKE_OK`")`n get_tree().quit()`n"|Set-Content -Encoding utf8NoBOM (Join-Path $d 'main.gd');"[gd_scene load_steps=2 format=3]`n[ext_resource path=`"res://main.gd`" type=`"Script`" id=`"1`"]`n[node name=`"Main`" type=`"Node`"]`nscript=ExtResource(`"1`")`n"|Set-Content -Encoding utf8NoBOM (Join-Path $d 'main.tscn');$o=(&$g --headless --path $d 2>&1|Out-String);A ($LASTEXITCODE-eq 0-and$o-match'FORGE_GODOT_SMOKE_OK') "Godot smoke failed $o";Write-Host "FORGE_GODOT_SMOKE_OK $n"}
$repo=$env:GITHUB_REPOSITORY;if(-not$repo){$repo='Ratwaredev/forge-studio-releases'};$dl=Join-Path $env:RUNNER_TEMP 'base0382';$inst=Join-Path $env:RUNNER_TEMP 'inst0382';$patched=Join-Path $env:RUNNER_TEMP 'forge0383';Remove-Item $dl,$inst,$patched -Recurse -Force -ErrorAction SilentlyContinue;New-Item -ItemType Directory -Force $dl|Out-Null;gh release download v0.38.2 --repo $repo --pattern 'Forge-Studio-Setup-0.38.2-x64.exe' --dir $dl;$exe=Join-Path $dl 'Forge-Studio-Setup-0.38.2-x64.exe';A (Test-Path $exe) '0.38.2 not downloaded';$sha=(Get-FileHash $exe -Algorithm SHA256).Hash.ToLowerInvariant();A ($sha-eq'6836b9a7a42ea713ae8124658f8a82183d698211b019e7de420a17f52b41c6ba') "Bad 0.38.2 SHA $sha";$p=Start-Process $exe -ArgumentList '/S',"/D=$inst" -Wait -PassThru;A ($p.ExitCode-eq 0) '0.38.2 install failed';Copy-Item $inst $patched -Recurse;Remove-Item (Join-Path $patched 'Uninstall Forge Studio.exe') -Force -ErrorAction SilentlyContinue;$app=Join-Path $patched 'resources\app';A ((node -p "require('$($app.Replace('\','/'))/package.json').version")-eq'0.38.2') 'Wrong base version';$g=Godot $app;$gv=(&$g --version 2>&1|Out-String).Trim();A ($gv-match'^4\.7\.1') "Wrong Godot $gv";$prov=Get-Content (Join-Path $app 'toolchains\godot\toolchain.json') -Raw|ConvertFrom-Json;A ($prov.sha256-eq'c7a289051eaefb460b0106b60e9cd5bee0ef55fd102dcb2bed1eb356cf3d90a1') 'Godot provenance changed';Smoke $g 'base'
$pkgPath=Join-Path $app 'package.json';$pkg=Get-Content $pkgPath -Raw|ConvertFrom-Json;$pkg.version='0.38.3';$pkg|ConvertTo-Json -Depth 100|Set-Content -Encoding utf8NoBOM $pkgPath;Copy-Item '.github/hotfix/0.38.3/forge-runtime-guard.js' (Join-Path $app 'public\forge-runtime-guard.js') -Force
$idxPath=Join-Path $app 'public\index.html';$idx=Get-Content $idxPath -Raw;$idx=$idx-replace'forge-runtime-guard\.js\?build=forge-v0382','forge-runtime-guard.js?build=forge-v0383';A ($idx-match'forge-v0383') 'Guard cache key failed';Set-Content -Encoding utf8NoBOM $idxPath $idx
$sPath=Join-Path $app 'public\product-surfaces.js';$s=Get-Content $sPath -Raw;A ($s-notmatch'MutationObserver') 'Renderer regression';$old=$s;$s=$s-replace'setInterval\(render,\s*1000\);?','';A ($s-ne$old) 'Idle product rerender not found';Set-Content -Encoding utf8NoBOM $sPath $s
$aPath=Join-Path $app 'public\app.js';$a=Get-Content $aPath -Raw;$old=$a;$a=$a.Replace('return ["godot", "next", "vite", "static"].includes(kind) || nodeUsesEmbeddedPreview(version) ? "embedded" : "native";','return ["next", "vite", "static"].includes(kind) || nodeUsesEmbeddedPreview(version) ? "embedded" : "native";');A ($a-ne$old) 'Godot default mode patch failed';$old=$a;$a=$a.Replace('state.pollTimer = setInterval(() => loadBootstrap({ quiet: true }).catch(() => undefined), 1600);','state.pollTimer = setInterval(() => loadBootstrap({ quiet: true }).catch(() => undefined), 2800);');A ($a-ne$old) 'Polling patch failed';Set-Content -Encoding utf8NoBOM $aPath $a
$agentPath=Join-Path $app 'dist\agent\index.js';$agent=Get-Content $agentPath -Raw;$old=$agent;$agent=$agent-replace'const prepareGodot = analysis\.kind === "godot" && \(isRun \|\| customGodotValidation\);','const prepareGodot = analysis.kind === "godot" && customGodotValidation;';A ($agent-ne$old) 'Godot duplicate import patch failed';Set-Content -Encoding utf8NoBOM $agentPath $agent
node --check (Join-Path $app 'public\forge-runtime-guard.js');node --check $sPath;node --check $aPath;A ((Get-Content $sPath -Raw)-notmatch'setInterval\(render') 'Idle loop remains';A ((Get-Content $agentPath -Raw)-notmatch'isRun \|\| customGodotValidation') 'Duplicate import remains';A ((Get-Content (Join-Path $app 'public\forge-runtime-guard.js') -Raw)-match'Del ZIP al proyecto listo para probar') 'UX purpose missing';Smoke $g 'patched';"PATCHED=$patched">>$env:GITHUB_ENV;"BASE_INSTALL=$inst">>$env:GITHUB_ENV;Write-Host 'FORGE_0383_PREPARED_OK'
